services:
  - type: web
    name: ai-task-manager-backend
    env: go
    plan: free
    buildCommand: go build -o main
    startCommand: ./main
    envVars:
      - key: GEMINI_API_KEY
        value: <your-gemini-key>
      - key: DATABASE_URL
        value: postgres://user:pass123@localhost/task_manager
